// Generated by klsl_wgsl_emitter from KLSL

@group(0) @binding(0) var<storage, read> edges: array<f32>;
@group(0) @binding(1) var<storage, read> adjacency: array<f32>;
@group(0) @binding(2) var<storage, read> field_in: array<f32>;
@group(0) @binding(3) var<storage, read_write> field_out: array<f32>;
@group(0) @binding(4) var<uniform> params: vec4<f32>;

@compute @workgroup_size(64, 1, 1)
fn propagate(@builtin(global_invocation_id) gid: vec3<u32>) {
    var i: u32 = gid.x;
    if (i >= params[0]) { return; }
    
    // Read field_in for this node (4 floats: value, geo_min, pad0, pad1)
    var own: f32 = field_in[i * 4 + 0];
    var geo: f32 = field_in[i * 4 + 1];
    
    // Read adjacency: [offset, count]
    var adj_offset: u32 = u32(adjacency[i * 2 + 0]);
    var adj_count: u32 = min(u32(adjacency[i * 2 + 1]), 8u);
    
    var accum: f32 = 0.0;
    for (var e: u32 = 0; e < adj_count; e++) {
        var idx: u32 = adj_offset + e;
        if (idx >= u32(params[1])) { break; }
        // Edge packed as 4 floats: a=edges[e*4+0], b=edges[e*4+1], dist=edges[e*4+2]
        var nb: u32 = u32(edges[idx * 4 + 1]);
        accum += field_in[nb * 4 + 0];
    }
    
    var neighbour_mean: f32 = (adj_count > 0u) ? (accum / f32(adj_count)) : own;
    var retain_val: f32 = params[2];
    
    field_out[i * 4 + 0] = retain_val * own + (1.0 - retain_val) * neighbour_mean;
    field_out[i * 4 + 1] = geo;
    field_out[i * 4 + 2] = 0.0;
    field_out[i * 4 + 3] = 0.0;
}
