// Generated by KLSL compiler v0.1
// Shader: pi_propagate

StructuredBuffer<float> edges : register(t1);
StructuredBuffer<float> adjacency : register(t2);
StructuredBuffer<float> field_in : register(t4);
RWStructuredBuffer<float> field_out : register(u1);
ConstantBuffer<float4> params : register(b0);

// pi_propagate.klsl — π-KUHUL graph diffusion pass
//
// One step of field diffusion over the mesh:
//   field_out(i) = a · field_in(i) + (1-a) · avg_neighbour(field_in)
//
// Compile:  python -m kuhul.kuhul_runner compile pi_propagate.klsl -o pi_propagate.wgsl
// Dispatch: [numthreads(64, 1, 1)]



// Edge adjacency buffer (packed as flattened array: [a, b, dist, _pad] per 4 floats)
// Node adjacency: [offset, count] per 2 uints
// Input field: [value, geo_min, _pad0, _pad1] per node
// Output field
// Params: nodeCount(u32), edgeCount(u32), retain(f32), _pad(f32)

[numthreads(64, 1, 1)]
void propagate(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint i = SV_DispatchThreadID.x;
    if (i >= params[0]) return;

    // Read field_in for this node (4 floats: value, geo_min, pad0, pad1)
    float own = field_in[i * 4 + 0];
    float geo = field_in[i * 4 + 1];

    // Read adjacency: [offset, count]
    uint adj_offset = uint(adjacency[i * 2 + 0]);
    uint adj_count  = min(uint(adjacency[i * 2 + 1]), 8u);

    float accum = 0.0;
    for (uint e = 0; e < adj_count; ++e) {
        uint idx = adj_offset + e;
        if (idx >= uint(params[1])) break;
        // Edge packed as 4 floats: a=edges[e*4+0], b=edges[e*4+1], dist=edges[e*4+2]
        uint nb = uint(edges[idx * 4 + 1]);
        accum += field_in[nb * 4 + 0];
    }

    float neighbour_mean = (adj_count > 0u) ? (accum / float(adj_count)) : own;
    float retain_val = params[2];

    field_out[i * 4 + 0] = retain_val * own + (1.0 - retain_val) * neighbour_mean;
    field_out[i * 4 + 1] = geo;
    field_out[i * 4 + 2] = 0.0;
    field_out[i * 4 + 3] = 0.0;
}


