// Generated by kxc for kernel MoEPhaseLLM
#include <d3d12.h>
#include <cstdint>

struct MoEPhaseLLMDispatchConfig {
  std::uint32_t seq_len = 0;
  std::uint32_t model_dim = 0;
  std::uint32_t head_dim = 0;
  std::uint32_t num_experts = 0;
  std::uint32_t phase_words = 0;
};

inline void Run_MoEPhaseLLM(ID3D12GraphicsCommandList* cmdList, const MoEPhaseLLMDispatchConfig& cfg) {
  if (!cmdList) return;
  // Backend-neutral IR lowered into a DirectX host stub.
  // variant=shared, heap_tier=1, binding_tier=1, uma=true
  // Route token logits, select top-2 experts, combine expert outputs, then apply phase match weighting.
  const UINT groupsX = (cfg.seq_len + 64 - 1) / 64;
  cmdList->Dispatch(groupsX, 1, 1);
}
