// Generated by kxc  kernel=fold_gradients  class=generic-compute
struct Params {
  seq_len    : u32,
  model_dim  : u32,
  head_dim   : u32,
  scale      : f32,
  num_experts: u32,
  phase_words: u32,
};

@group(0) @binding(0) var<uniform>            params     : Params;
@group(0) @binding(1) var<storage, read>      input_data : array<f32>;
@group(0) @binding(2) var<storage, read_write>output_data: array<f32>;

@compute @workgroup_size(32, 1, 1)
fn CSMain(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  if (i >= params.seq_len) { return; }
  output_data[i] = input_data[i];
}
