// Generated by kxc for kernel fold_gradients
#include <d3d12.h>
#include <cstdint>

struct fold_gradientsDispatchConfig {
  std::uint32_t seq_len = 0;
  std::uint32_t model_dim = 0;
  std::uint32_t head_dim = 0;
  std::uint32_t num_experts = 0;
  std::uint32_t phase_words = 0;
};

inline void Run_fold_gradients(ID3D12GraphicsCommandList* cmdList, const fold_gradientsDispatchConfig& cfg) {
  if (!cmdList) return;
  // Backend-neutral IR lowered into a DirectX host stub.
  // variant=shared, heap_tier=1, binding_tier=1, uma=true
  // Generic compute path.
  const UINT groupsX = (cfg.seq_len + 32 - 1) / 32;
  cmdList->Dispatch(groupsX, 1, 1);
}
