// Generated by kxc for kernel fold_gradients
// OpenCL C 1.2 — kxc backend: opencl_1_2

__kernel void CSMain(
    __global const float* In,
    __global float* Out,
    const uint n)
{
    const uint i = (uint)get_global_id(0);
    if (i >= n) return;
    Out[i] = In[i];
}
