// Generated by kxc  kernel=fold_clamp  class=generic-compute
// variant=shared
cbuffer Params : register(b0)
{
    uint seq_len;
    uint model_dim;
    uint head_dim;
    float scale;
    uint num_experts;
    uint phase_words;
};

StructuredBuffer<float>   X    : register(t0);
StructuredBuffer<float>   Wqkv : register(t1);
RWStructuredBuffer<float> Out  : register(u0);

[numthreads(64, 1, 1)]
void CSMain(uint3 tid : SV_DispatchThreadID)
{
    uint i = tid.x;
    if (i >= seq_len) return;
    Out[i] = X[i];
}
