// Generated by kxc for kernel FusedAttention
// OpenCL C 1.2 — kxc backend: opencl_1_2

__kernel void CSMain(
    __global const float* A,
    __global const float* B,
    __global float* C,
    const uint M,
    const uint N,
    const uint K,
    const float scale,
    const uint model_dim,
    const uint head_dim)
{
    const uint col = (uint)get_global_id(0);
    const uint row = (uint)get_global_id(1);
    if (row >= M || col >= N) return;
    float acc = 0.0f;
    for (uint k = 0u; k < K; k++) {
        acc += A[row * K + k] * B[k * N + col];
    }
    // softmax applied per-row; caller normalises
    acc *= scale;
    C[row * N + col] = acc;
}
