// Generated by kxc for kernel neural_layer_kuhul
#include <d3d12.h>
#include <cstdint>

struct neural_layer_kuhulDispatchConfig {
  std::uint32_t seq_len = 0;
  std::uint32_t model_dim = 0;
  std::uint32_t head_dim = 0;
  std::uint32_t num_experts = 0;
  std::uint32_t phase_words = 0;
};

inline void Run_neural_layer_kuhul(ID3D12GraphicsCommandList* cmdList, const neural_layer_kuhulDispatchConfig& cfg) {
  if (!cmdList) return;
  // Backend-neutral IR lowered into a DirectX host stub.
  // variant=shared, heap_tier=1, binding_tier=1, uma=true
  // Generic compute path.
  const UINT groupsX = (cfg.seq_len + 32 - 1) / 32;
  cmdList->Dispatch(groupsX, 16, 1);
}
