// Generated by kxc for kernel MoEPhaseLLM
struct Params {
  seq_len: u32,
  model_dim: u32,
  head_dim: u32,
  scale: f32,
  num_experts: u32,
  phase_words: u32,
};

@group(0) @binding(0) var<uniform> params : Params;
@group(0) @binding(1) var<storage, read> hidden_states : array<f32>;
@group(0) @binding(2) var<storage, read> router_weights : array<f32>;
@group(0) @binding(3) var<storage, read> expert_outputs : array<f32>;
@group(0) @binding(4) var<storage, read> phase_words : array<u32>;
@group(0) @binding(5) var<storage, read_write> combined : array<f32>;
@group(0) @binding(6) var<storage, read_write> route_indices : array<u32>;
@group(0) @binding(7) var<storage, read_write> route_weights : array<f32>;

fn phase_bias(expert_index: u32) -> f32 {
  var total: f32 = 0.0;
  for (var i: u32 = 0u; i < params.phase_words; i = i + 1u) {
    total = total + f32(phase_words[expert_index * params.phase_words + i] & 255u);
  }
  return total / max(1.0, f32(params.phase_words) * 255.0);
}

@compute @workgroup_size(32, 1, 1)
fn CSMain(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= params.seq_len) { return; }
  var best_idx: u32 = 0u;
  var second_idx: u32 = 0u;
  var best_score: f32 = -1e30;
  var second_score: f32 = -1e30;
  for (var expert: u32 = 0u; expert < params.num_experts; expert = expert + 1u) {
    var score: f32 = phase_bias(expert);
    for (var d: u32 = 0u; d < min(params.model_dim, 8u); d = d + 1u) {
      score = score + hidden_states[i * params.model_dim + d] * router_weights[d * params.num_experts + expert];
    }
    if (score > best_score) {
      second_score = best_score; second_idx = best_idx; best_score = score; best_idx = expert;
    } else if (score > second_score) {
      second_score = score; second_idx = expert;
    }
  }
  let eb = exp(best_score);
  let es = exp(second_score);
  let denom = max(eb + es, 1e-6);
  let w0 = eb / denom;
  let w1 = es / denom;
  route_indices[i * 2u] = best_idx;
  route_indices[i * 2u + 1u] = second_idx;
  route_weights[i * 2u] = w0;
  route_weights[i * 2u + 1u] = w1;
  for (var d: u32 = 0u; d < params.head_dim; d = d + 1u) {
    let a = expert_outputs[(best_idx * params.seq_len + i) * params.head_dim + d];
    let b = expert_outputs[(second_idx * params.seq_len + i) * params.head_dim + d];
    combined[i * params.head_dim + d] = a * w0 + b * w1;
  }
}
