// Generated by kxc for kernel MoEPhaseLLM
// variant=wave
cbuffer Params : register(b0)
{
    uint seq_len;
    uint model_dim;
    uint head_dim;
    float scale;
    uint num_experts;
    uint phase_words;
};

StructuredBuffer<float> HiddenStates : register(t0);
StructuredBuffer<float> RouterWeights : register(t1);
StructuredBuffer<float> ExpertOutputs : register(t2);
StructuredBuffer<uint> PhaseArrayData : register(t3);
RWStructuredBuffer<float> Combined : register(u0);
RWStructuredBuffer<uint> RouteIndices : register(u1);
RWStructuredBuffer<float> RouteWeights : register(u2);

float phase_bias(uint expertIndex)
{
    float total = 0.0f;
    [loop]
    for (uint i = 0; i < phase_words; ++i) {
        total += (float)(PhaseArrayData[expertIndex * phase_words + i] & 0xFF);
    }
    return total / max(1.0f, (float)(phase_words * 255u));
}

[numthreads(32, 1, 1)]
void CSMain(uint3 tid : SV_DispatchThreadID)
{
    uint i = tid.x;
    if (i >= seq_len) return;
    uint bestIdx = 0;
    uint secondIdx = 0;
    float bestScore = -3.402823e38f;
    float secondScore = -3.402823e38f;
    [loop]
    for (uint expert = 0; expert < num_experts; ++expert) {
        float score = phase_bias(expert);
        [unroll]
        for (uint d = 0; d < min(model_dim, 8u); ++d) {
            score += HiddenStates[i * model_dim + d] * RouterWeights[d * num_experts + expert];
        }
        if (score > bestScore) {
            secondScore = bestScore;
            secondIdx = bestIdx;
            bestScore = score;
            bestIdx = expert;
        } else if (score > secondScore) {
            secondScore = score;
            secondIdx = expert;
        }
    }
    float e0 = exp(bestScore);
    float e1 = exp(secondScore);
    float denom = max(e0 + e1, 1e-6f);
    float w0 = e0 / denom;
    float w1 = e1 / denom;
    RouteIndices[i * 2] = bestIdx;
    RouteIndices[i * 2 + 1] = secondIdx;
    RouteWeights[i * 2] = w0;
    RouteWeights[i * 2 + 1] = w1;
    for (uint d = 0; d < head_dim; ++d) {
        float a = ExpertOutputs[(bestIdx * seq_len + i) * head_dim + d];
        float b = ExpertOutputs[(secondIdx * seq_len + i) * head_dim + d];
        float combined = a * w0 + b * w1;
        combined *= (0.5f + 0.5f * phase_bias(bestIdx));
        Combined[i * head_dim + d] = combined;
    }
}
