#version 300 es
precision highp float;

// Generated by kxc for kernel fold_adam
// WebGL2 GLSL ES 3.0 — kxc backend: angle_d3d11

uniform highp sampler2D u_input_0;
uniform ivec2 u_shape;
out vec4 fragColor;

void main() {
    ivec2 ij = ivec2(gl_FragCoord.xy);
    if (ij.x >= u_shape.x || ij.y >= u_shape.y) discard;
    float v = texelFetch(u_input_0, ij, 0).r;
    fragColor = vec4(v, 0.0, 0.0, 1.0);
}
