// Generated by kxc for kernel fold_adam
#include <algorithm>
#include <cstdint>
#include <vector>

struct fold_adamCpuConfig {
  std::uint32_t seq_len = 0;
  std::uint32_t model_dim = 0;
  std::uint32_t head_dim = 0;
  std::uint32_t num_experts = 0;
};

inline void Run_fold_adam_Cpu(const fold_adamCpuConfig& cfg) {
  (void)cfg;
  // CPU fallback generated from backend-neutral IR.
  // wave_ops=false, heap_tier=1, binding_tier=1
  // Generic scalar fallback.
}
