#include "emit_hlsl.h"
#include <fstream>

bool emit_hlsl(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    f << "// Generated by kxc  kernel=" << d.name
      << "  class=" << ir.kernelClass << "\n";

    // ── needsMeshlet → Amplification + Mesh shader pair ──────────────────────
    // Pattern from d3d12-meshlets/src/MeshletCull/MeshletAS.hlsl
    if (d.needsMeshlet) {
        f << "// variant=mesh_pipeline  requires=D3D_SHADER_MODEL_6_5\n\n";
        f << "struct MeshInfo {\n";
        f << "    uint MeshletCount;\n";
        f << "    uint LastMeshletSize;\n";
        f << "    uint4 CullData;   // packed cone + sphere per meshlet\n";
        f << "};\n\n";
        f << "struct MeshletBounds {\n";
        f << "    float3 Center;  float Radius;\n";
        f << "    float3 ConeApex;\n";
        f << "    float3 ConeAxis; float ConeCutoff;\n";
        f << "};\n\n";
        f << "ConstantBuffer<MeshInfo>       MeshCB     : register(b0);\n";
        f << "StructuredBuffer<MeshletBounds> Bounds     : register(t0);\n";
        f << "RWStructuredBuffer<uint>        Visibility : register(u0);\n\n";
        f << "groupshared uint gs_VisibleCount;\n\n";
        f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
        f << "void CSMain(uint3 dtid : SV_DispatchThreadID, uint3 gtid : SV_GroupThreadID)\n{\n";
        f << "    if (gtid.x == 0) gs_VisibleCount = 0;\n";
        f << "    GroupMemoryBarrierWithGroupSync();\n\n";
        f << "    uint mi = dtid.x;\n";
        f << "    if (mi >= MeshCB.MeshletCount) return;\n\n";
        f << "    MeshletBounds mb = Bounds[mi];\n";
        f << "    // Cone test: dot(viewDir, -coneAxis) < coneCutoff → backfacing\n";
        f << "    // Full implementation: load view pos from cbuffer and test against apex\n";
        f << "    bool visible = true;  // extend with frustum test here\n\n";
        f << "    if (visible) {\n";
        f << "        uint slot;\n";
        f << "        InterlockedAdd(gs_VisibleCount, 1, slot);\n";
        f << "        Visibility[mi / 32] |= (1u << (mi % 32));\n";
        f << "    }\n";
        f << "}\n";
        return true;
    }

    // ── needsNormalCompute ────────────────────────────────────────────────────
    // Two-pass normal computation (same pattern as WebGPU, using InterlockedAdd)
    if (d.needsNormalCompute) {
        f << "// variant=compute_normals  pass=accumulate\n\n";
        f << "cbuffer NormalParams : register(b0) {\n";
        f << "    uint TriCount;\n";
        f << "    uint VertexCount;\n";
        f << "    uint VertexStride;  // float elements\n";
        f << "    uint PosOffset;     // float elements\n";
        f << "};\n\n";
        f << "StructuredBuffer<float>    Positions  : register(t0); // scalar array\n";
        f << "StructuredBuffer<uint>     Indices    : register(t1);\n";
        f << "RWStructuredBuffer<int>    NormalAcc  : register(u0); // 3 ints/vertex, ×65536\n\n";
        f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
        f << "void CSNormalAccum(uint3 dtid : SV_DispatchThreadID)\n{\n";
        f << "    uint tri = dtid.x;\n";
        f << "    if (tri >= TriCount) return;\n\n";
        f << "    uint i0 = Indices[tri * 3], i1 = Indices[tri * 3 + 1], i2 = Indices[tri * 3 + 2];\n";
        f << "    uint b0 = i0 * VertexStride + PosOffset;\n";
        f << "    uint b1 = i1 * VertexStride + PosOffset;\n";
        f << "    uint b2 = i2 * VertexStride + PosOffset;\n";
        f << "    float3 p0 = float3(Positions[b0], Positions[b0+1], Positions[b0+2]);\n";
        f << "    float3 p1 = float3(Positions[b1], Positions[b1+1], Positions[b1+2]);\n";
        f << "    float3 p2 = float3(Positions[b2], Positions[b2+1], Positions[b2+2]);\n";
        f << "    float3 n  = cross(p1 - p0, p2 - p0);\n\n";
        f << "    int3 ni = int3(n * 65536.0f);\n";
        f << "    uint verts[3] = { i0, i1, i2 };\n";
        f << "    for (uint k = 0; k < 3; ++k) {\n";
        f << "        InterlockedAdd(NormalAcc[verts[k] * 3],     ni.x);\n";
        f << "        InterlockedAdd(NormalAcc[verts[k] * 3 + 1], ni.y);\n";
        f << "        InterlockedAdd(NormalAcc[verts[k] * 3 + 2], ni.z);\n";
        f << "    }\n";
        f << "}\n";
        return true;
    }

    // ── needsTangentFrame ─────────────────────────────────────────────────────
    if (d.needsTangentFrame) {
        f << "// variant=tangent_frame\n\n";
        f << "cbuffer TangentParams : register(b0) {\n";
        f << "    uint TriCount; uint VertexStride;\n";
        f << "    uint PosOffset; uint UVOffset; uint TanOffset; uint BitanOffset;\n";
        f << "};\n\n";
        f << "StructuredBuffer<float>   VB    : register(t0);\n";
        f << "StructuredBuffer<uint>    IB    : register(t1);\n";
        f << "RWStructuredBuffer<float> VBOut : register(u0);\n\n";
        f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
        f << "void CSMain(uint3 dtid : SV_DispatchThreadID)\n{\n";
        f << "    uint tri = dtid.x;\n";
        f << "    if (tri >= TriCount) return;\n\n";
        f << "    uint i0 = IB[tri*3], i1 = IB[tri*3+1], i2 = IB[tri*3+2];\n";
        f << "    float3 p0 = float3(VB[i0*VertexStride+PosOffset], VB[i0*VertexStride+PosOffset+1], VB[i0*VertexStride+PosOffset+2]);\n";
        f << "    float3 p1 = float3(VB[i1*VertexStride+PosOffset], VB[i1*VertexStride+PosOffset+1], VB[i1*VertexStride+PosOffset+2]);\n";
        f << "    float3 p2 = float3(VB[i2*VertexStride+PosOffset], VB[i2*VertexStride+PosOffset+1], VB[i2*VertexStride+PosOffset+2]);\n";
        f << "    float2 uv0 = float2(VB[i0*VertexStride+UVOffset], VB[i0*VertexStride+UVOffset+1]);\n";
        f << "    float2 uv1 = float2(VB[i1*VertexStride+UVOffset], VB[i1*VertexStride+UVOffset+1]);\n";
        f << "    float2 uv2 = float2(VB[i2*VertexStride+UVOffset], VB[i2*VertexStride+UVOffset+1]);\n\n";
        f << "    float3 dp1 = p1-p0, dp2 = p2-p0;\n";
        f << "    float2 duv1 = uv1-uv0, duv2 = uv2-uv0;\n";
        f << "    float det = duv1.x*duv2.y - duv2.x*duv1.y;\n";
        f << "    float inv = (abs(det) > 1e-6f) ? 1.0f/det : 0.0f;\n";
        f << "    float3 tan   = normalize((dp1*duv2.y - dp2*duv1.y)*inv);\n";
        f << "    float3 bitan = normalize((dp2*duv1.x - dp1*duv2.x)*inv);\n\n";
        f << "    uint verts[3] = { i0, i1, i2 };\n";
        f << "    for (uint k = 0; k < 3; ++k) {\n";
        f << "        uint bt = verts[k]*VertexStride + TanOffset;\n";
        f << "        uint bb = verts[k]*VertexStride + BitanOffset;\n";
        f << "        VBOut[bt]=tan.x;   VBOut[bt+1]=tan.y;   VBOut[bt+2]=tan.z;\n";
        f << "        VBOut[bb]=bitan.x; VBOut[bb+1]=bitan.y; VBOut[bb+2]=bitan.z;\n";
        f << "    }\n";
        f << "}\n";
        return true;
    }

    // ── needsVertexProcess ────────────────────────────────────────────────────
    if (d.needsVertexProcess) {
        f << "// variant=vertex_process\n\n";
        f << "cbuffer VertexParams : register(b0) {\n";
        f << "    uint VertexCount; uint InStride; uint InOffset;\n";
        f << "    uint OutStride;   uint OutOffset; float Scale;\n";
        f << "};\n\n";
        f << "StructuredBuffer<float>   VertIn  : register(t0);\n";
        f << "RWStructuredBuffer<float> VertOut : register(u0);\n\n";
        f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
        f << "void CSMain(uint3 dtid : SV_DispatchThreadID)\n{\n";
        f << "    uint vi = dtid.x;\n";
        f << "    if (vi >= VertexCount) return;\n\n";
        f << "    uint src = vi * InStride  + InOffset;\n";
        f << "    uint dst = vi * OutStride + OutOffset;\n";
        f << "    VertOut[dst]   = VertIn[src]   * Scale;\n";
        f << "    VertOut[dst+1] = VertIn[src+1] * Scale;\n";
        f << "    VertOut[dst+2] = VertIn[src+2] * Scale;\n";
        f << "}\n";
        return true;
    }

    // ── default (attention / matmul / phase / generic) ────────────────────────
    f << "// variant=shared\n";
    f << "cbuffer Params : register(b0)\n{\n";
    f << "    uint seq_len;\n    uint model_dim;\n    uint head_dim;\n";
    f << "    float scale;\n    uint num_experts;\n    uint phase_words;\n";
    f << "};\n\n";
    f << "StructuredBuffer<float>   X    : register(t0);\n";
    f << "StructuredBuffer<float>   Wqkv : register(t1);\n";
    f << "RWStructuredBuffer<float> Out  : register(u0);\n\n";
    f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
    f << "void CSMain(uint3 tid : SV_DispatchThreadID)\n{\n";
    f << "    uint i = tid.x;\n";
    f << "    if (i >= seq_len) return;\n";
    if (d.needsMatMul && d.needsSoftmax) {
        f << "    float acc = 0.0f;\n";
        f << "    for (uint d = 0; d < min(model_dim, head_dim); ++d)\n";
        f << "        acc += X[i * model_dim + d] * Wqkv[d * head_dim + d];\n";
        f << "    Out[i] = acc * scale;\n";
    } else if (d.needsMatMul) {
        f << "    float acc = 0.0f;\n";
        f << "    for (uint d = 0; d < min(model_dim, head_dim); ++d)\n";
        f << "        acc += X[i * model_dim + d] * Wqkv[d * (3 * head_dim) + d];\n";
        f << "    Out[i * head_dim] = acc;\n";
    } else if (d.needsPhaseMatch) {
        f << "    float x  = X[i];\n";
        f << "    float dx = X[i + seq_len];\n";
        f << "    Out[i] = x + 0.01f * dx;\n";
    } else {
        f << "    Out[i] = X[i];\n";
    }
    f << "}\n";
    return true;
}
