#include "emit_opencl.h"
#include <fstream>
#include <string>

bool emit_opencl(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot open " + outPath; return false; }

    auto& d = ir.desc;
    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "// OpenCL C 1.2 — kxc backend: opencl_1_2\n\n";

    if (d.needsMatMul) {
        // GEMM kernel matching the lowered cssc_gemm-matmul pattern
        f << "__kernel void CSMain(\n";
        f << "    __global const float* A,\n";
        f << "    __global const float* B,\n";
        f << "    __global float* C,\n";
        f << "    const uint M,\n";
        f << "    const uint N,\n";
        f << "    const uint K,\n";
        f << "    const float scale,\n";
        f << "    const uint model_dim,\n";
        f << "    const uint head_dim)\n";
        f << "{\n";
        f << "    const uint col = (uint)get_global_id(0);\n";
        f << "    const uint row = (uint)get_global_id(1);\n";
        f << "    if (row >= M || col >= N) return;\n";
        f << "    float acc = 0.0f;\n";
        f << "    for (uint k = 0u; k < K; k++) {\n";
        f << "        acc += A[row * K + k] * B[k * N + col];\n";
        f << "    }\n";
        if (d.needsSoftmax) {
            f << "    // softmax applied per-row; caller normalises\n";
            f << "    acc *= scale;\n";
        }
        f << "    C[row * N + col] = acc;\n";
        f << "}\n";

    } else if (d.needsMoERoute) {
        // top-2 MoE routing
        f << "__kernel void CSMain(\n";
        f << "    __global const float* gate_logits,\n";
        f << "    __global int* expert_ids,\n";
        f << "    __global float* expert_weights,\n";
        f << "    const uint seq_len,\n";
        f << "    const uint num_experts)\n";
        f << "{\n";
        f << "    const uint t = (uint)get_global_id(0);\n";
        f << "    if (t >= seq_len) return;\n";
        f << "    const __global float* row = gate_logits + t * num_experts;\n";
        f << "    int top0 = 0, top1 = 1;\n";
        f << "    if (row[1] > row[0]) { top0 = 1; top1 = 0; }\n";
        f << "    for (uint e = 2u; e < num_experts; e++) {\n";
        f << "        if (row[e] > row[top0]) { top1 = top0; top0 = (int)e; }\n";
        f << "        else if (row[e] > row[top1]) top1 = (int)e;\n";
        f << "    }\n";
        f << "    expert_ids[t * 2 + 0] = top0;\n";
        f << "    expert_ids[t * 2 + 1] = top1;\n";
        f << "    float w0 = exp(row[top0]), w1 = exp(row[top1]);\n";
        f << "    float norm = w0 + w1 + 1e-8f;\n";
        f << "    expert_weights[t * 2 + 0] = w0 / norm;\n";
        f << "    expert_weights[t * 2 + 1] = w1 / norm;\n";
        f << "}\n";

    } else if (d.needsPhaseMatch) {
        // semantic tensor evolution matching tensor_evolve.cl
        f << "__kernel void CSMain(\n";
        f << "    __global float* tensor,\n";
        f << "    __global float* scratch,\n";
        f << "    const int batch,\n";
        f << "    const int sequence,\n";
        f << "    const int hidden,\n";
        f << "    const float dt,\n";
        f << "    const float damping)\n";
        f << "{\n";
        f << "    const int idx = (int)get_global_id(0);\n";
        f << "    const int total = batch * sequence * hidden;\n";
        f << "    if (idx >= total) return;\n";
        f << "    const float x = tensor[idx];\n";
        f << "    const float dx = damping * x + scratch[idx];\n";
        f << "    tensor[idx] = x + dt * dx;\n";
        f << "    scratch[idx] = dx;\n";
        f << "}\n";

    } else if (d.needsDecompress) {
        // INT4 decompress for kvInt4
        f << "__kernel void CSMain(\n";
        f << "    __global const uchar* packed,\n";
        f << "    __global float* out,\n";
        f << "    const uint n)\n";
        f << "{\n";
        f << "    const uint i = (uint)get_global_id(0);\n";
        f << "    if (i >= n / 2) return;\n";
        f << "    uchar b = packed[i];\n";
        f << "    int lo = (int)(b & 0x0Fu) - 8;\n";
        f << "    int hi = (int)(b >> 4)   - 8;\n";
        f << "    out[i * 2 + 0] = (float)lo;\n";
        f << "    out[i * 2 + 1] = (float)hi;\n";
        f << "}\n";

    } else {
        // generic passthrough matching the generic-compute class
        f << "__kernel void CSMain(\n";
        f << "    __global const float* In,\n";
        f << "    __global float* Out,\n";
        f << "    const uint n)\n";
        f << "{\n";
        f << "    const uint i = (uint)get_global_id(0);\n";
        f << "    if (i >= n) return;\n";
        f << "    Out[i] = In[i];\n";
        f << "}\n";
    }

    return true;
}
