#include "emit_cpu.h"
#include <fstream>

bool emit_cpu(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    std::string cfg = d.name + "CpuConfig";

    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "#include <algorithm>\n#include <cstdint>\n#include <vector>\n\n";
    f << "struct " << cfg << " {\n";
    f << "  std::uint32_t seq_len = 0;\n";
    f << "  std::uint32_t model_dim = 0;\n";
    f << "  std::uint32_t head_dim = 0;\n";
    f << "  std::uint32_t num_experts = 0;\n";
    f << "};\n\n";
    f << "inline void Run_" << d.name << "_Cpu(const " << cfg << "& cfg) {\n";
    f << "  (void)cfg;\n";
    f << "  // CPU fallback generated from backend-neutral IR.\n";
    f << "  // wave_ops=" << (ir.waveOps ? "true" : "false")
      << ", heap_tier=" << ir.heapTier
      << ", binding_tier=" << ir.bindingTier << "\n";
    f << "  // Generic scalar fallback.\n";
    f << "}\n";
    return true;
}
