#include "emit_wgsl.h"
#include <fstream>

bool emit_wgsl(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "struct Params {\n";
    f << "  seq_len: u32,\n  model_dim: u32,\n  head_dim: u32,\n";
    f << "  scale: f32,\n  num_experts: u32,\n  phase_words: u32,\n};\n\n";
    f << "@group(0) @binding(0) var<uniform> params : Params;\n";
    f << "@group(0) @binding(1) var<storage, read> input_data : array<f32>;\n";
    f << "@group(0) @binding(2) var<storage, read_write> output_data : array<f32>;\n\n";
    f << "@compute @workgroup_size(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")\n";
    f << "fn CSMain(@builtin(global_invocation_id) gid : vec3<u32>) {\n";
    f << "  let i = gid.x;\n";
    f << "  if (i >= params.seq_len) { return; }\n";
    f << "  output_data[i] = input_data[i];\n";
    f << "}\n";
    return true;
}
