#include "emit_hlsl.h"
#include <fstream>

bool emit_hlsl(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "// variant=shared\n";
    f << "cbuffer Params : register(b0)\n{\n";
    f << "    uint seq_len;\n";
    f << "    uint model_dim;\n";
    f << "    uint head_dim;\n";
    f << "    float scale;\n";
    f << "    uint num_experts;\n";
    f << "    uint phase_words;\n";
    f << "};\n\n";
    f << "StructuredBuffer<float> X : register(t0);\n";
    f << "StructuredBuffer<float> Wqkv : register(t1);\n";
    f << "RWStructuredBuffer<float> Out : register(u0);\n\n";
    f << "[numthreads(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")]\n";
    f << "void CSMain(uint3 tid : SV_DispatchThreadID)\n{\n";
    f << "    uint i = tid.x;\n";
    f << "    if (i >= seq_len) return;\n";
    f << "    float acc = 0.0f;\n";
    f << "    for (uint d = 0; d < min(model_dim, head_dim); ++d) {\n";
    f << "        float x = X[i * model_dim + d];\n";
    f << "        float w = Wqkv[d * (3 * head_dim) + d];\n";
    f << "        acc += x * w;\n";
    f << "    }\n";
    f << "    Out[i * head_dim] = acc;\n";
    f << "}\n";
    return true;
}
