#include "emit_webgl2.h"
#include <fstream>
#include <string>

bool emit_webgl2(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot open " + outPath; return false; }

    auto& d = ir.desc;
    f << "#version 300 es\n";
    f << "precision highp float;\n\n";
    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "// WebGL2 GLSL ES 3.0 — kxc backend: angle_d3d11\n\n";

    if (d.needsMatMul) {
        // matches matmul.frag: two texture inputs, output via fragColor
        f << "uniform highp sampler2D u_input_0; // A [M,K]\n";
        f << "uniform highp sampler2D u_input_1; // B [K,N]\n";
        f << "uniform ivec2 u_A_shape;            // [M, K]\n";
        f << "uniform ivec2 u_B_shape;            // [K, N]\n";
        f << "uniform ivec2 u_C_shape;            // [M, N]\n";
        if (d.needsSoftmax) {
            f << "uniform float u_scale;\n";
        }
        f << "out vec4 fragColor;\n\n";
        f << "void main() {\n";
        f << "    ivec2 ij = ivec2(gl_FragCoord.xy);\n";
        f << "    if (ij.x >= u_C_shape.x || ij.y >= u_C_shape.y) discard;\n";
        f << "    float sum = 0.0;\n";
        f << "    for (int k = 0; k < u_A_shape.y; ++k) {\n";
        f << "        sum += texelFetch(u_input_0, ivec2(ij.x, k), 0).r\n";
        f << "             * texelFetch(u_input_1, ivec2(k, ij.y), 0).r;\n";
        f << "    }\n";
        if (d.needsSoftmax) {
            f << "    sum *= u_scale;\n";
        }
        f << "    fragColor = vec4(sum, 0.0, 0.0, 1.0);\n";
        f << "}\n";

    } else if (d.needsMoERoute) {
        // texture-based top-1 routing (WebGL2 can't do top-2 in a single pass easily)
        f << "uniform highp sampler2D u_gate_logits; // [seq_len, num_experts]\n";
        f << "uniform int u_num_experts;\n";
        f << "out vec4 fragColor;\n\n";
        f << "void main() {\n";
        f << "    int t = int(gl_FragCoord.y);\n";
        f << "    float best = texelFetch(u_gate_logits, ivec2(0, t), 0).r;\n";
        f << "    int best_e = 0;\n";
        f << "    for (int e = 1; e < u_num_experts; ++e) {\n";
        f << "        float v = texelFetch(u_gate_logits, ivec2(e, t), 0).r;\n";
        f << "        if (v > best) { best = v; best_e = e; }\n";
        f << "    }\n";
        f << "    fragColor = vec4(float(best_e), best, 0.0, 1.0);\n";
        f << "}\n";

    } else if (d.needsPhaseMatch) {
        // tensor field readback — matches fieldgraph_100d.frag
        f << "uniform highp sampler2D uFieldgraph;\n";
        f << "uniform int uDimensions;\n";
        f << "uniform int uRecord;\n";
        f << "uniform int uColumn;\n";
        f << "out vec4 fragColor;\n\n";
        f << "void main() {\n";
        f << "    int column = clamp(uColumn, 0, uDimensions - 1);\n";
        f << "    int record = max(uRecord, 0);\n";
        f << "    float value = texelFetch(uFieldgraph, ivec2(column, record), 0).r;\n";
        f << "    fragColor = vec4(value, 0.0, 0.0, 1.0);\n";
        f << "}\n";

    } else if (d.needsDecompress) {
        // gravity corrective field — matches gravity_corrective.frag
        f << "uniform highp sampler2D u_input_0;  // field tensor\n";
        f << "uniform highp sampler2D u_gravity;   // gravity weights\n";
        f << "uniform ivec2 u_shape;\n";
        f << "out vec4 fragColor;\n\n";
        f << "void main() {\n";
        f << "    ivec2 ij = ivec2(gl_FragCoord.xy);\n";
        f << "    if (ij.x >= u_shape.x || ij.y >= u_shape.y) discard;\n";
        f << "    float v = texelFetch(u_input_0, ij, 0).r;\n";
        f << "    float g = texelFetch(u_gravity,  ij, 0).r;\n";
        f << "    fragColor = vec4(v + g, 0.0, 0.0, 1.0);\n";
        f << "}\n";

    } else {
        // generic passthrough
        f << "uniform highp sampler2D u_input_0;\n";
        f << "uniform ivec2 u_shape;\n";
        f << "out vec4 fragColor;\n\n";
        f << "void main() {\n";
        f << "    ivec2 ij = ivec2(gl_FragCoord.xy);\n";
        f << "    if (ij.x >= u_shape.x || ij.y >= u_shape.y) discard;\n";
        f << "    float v = texelFetch(u_input_0, ij, 0).r;\n";
        f << "    fragColor = vec4(v, 0.0, 0.0, 1.0);\n";
        f << "}\n";
    }

    return true;
}
