#include "emit_cpp.h"
#include <fstream>

bool emit_cpp(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    std::string cfg = d.name + "DispatchConfig";

    f << "// Generated by kxc for kernel " << d.name << "\n";
    f << "#include <d3d12.h>\n#include <cstdint>\n\n";
    f << "struct " << cfg << " {\n";
    f << "  std::uint32_t seq_len = 0;\n";
    f << "  std::uint32_t model_dim = 0;\n";
    f << "  std::uint32_t head_dim = 0;\n";
    f << "  std::uint32_t num_experts = 0;\n";
    f << "  std::uint32_t phase_words = 0;\n";
    f << "};\n\n";
    f << "inline void Run_" << d.name
      << "(ID3D12GraphicsCommandList* cmdList, const " << cfg << "& cfg) {\n";
    f << "  if (!cmdList) return;\n";
    f << "  // Backend-neutral IR lowered into a DirectX host stub.\n";
    f << "  // variant=shared, heap_tier=" << ir.heapTier
      << ", binding_tier=" << ir.bindingTier
      << ", uma=" << (ir.uma ? "true" : "false") << "\n";
    f << "  // Generic compute path.\n";
    f << "  const UINT groupsX = (cfg.seq_len + " << d.threads[0] << " - 1) / " << d.threads[0] << ";\n";
    f << "  cmdList->Dispatch(groupsX, 1, 1);\n";
    f << "}\n";
    return true;
}
