#include "emit_wgsl.h"
#include <fstream>

// WebGPU compute vertex data patterns from toji.dev/webgpu-best-practices/compute-vertex-data.html
// Key rules enforced by this emitter:
//   1. array<f32> not array<vec3f> — vec3f has 16-byte alignment in WGSL (wastes 4B/element)
//   2. stride + offset as uniforms in f32 element units, not bytes
//   3. workgroup early-exit before any memory access
//   4. normal accumulation uses quantised atomicAdd (f32 → i32 × QUANT, then /QUANT)
//   5. multi-pass algorithms (accumulate then normalise) are separate dispatches

bool emit_wgsl(const KernelIR& ir, const std::string& outPath, std::string& err) {
    std::ofstream f(outPath);
    if (!f) { err = "cannot write: " + outPath; return false; }

    const auto& d = ir.desc;
    f << "// Generated by kxc  kernel=" << d.name
      << "  class=" << ir.kernelClass << "\n";

    // ── needsNormalCompute ────────────────────────────────────────────────────
    // Pass 1: per-triangle face-normal accumulation into atomic<i32> accumulators.
    // Pass 2 (separate dispatch): normalise by dividing by QUANT and length.
    if (d.needsNormalCompute) {
        f << R"(
// PASS 1 of 2: accumulate face normals per vertex (atomicAdd, quantised).
// Dispatch: ceil(tri_count / 64) × 1 × 1
// After this pass, dispatch NormalNormalise below over vertex_count.

struct NormalUniforms {
  tri_count    : u32,
  vertex_count : u32,
  vertex_stride: u32,   // f32 elements between consecutive vertex starts
  pos_offset   : u32,   // f32 elements from vertex start to position.x
};

@group(0) @binding(0) var<uniform>              uniforms   : NormalUniforms;
@group(0) @binding(1) var<storage, read>        positions  : array<f32>;   // scalar — no vec3f
@group(0) @binding(2) var<storage, read>        indices    : array<u32>;
@group(0) @binding(3) var<storage, read_write>  normals_acc: array<atomic<i32>>; // 3 i32 per vertex

const QUANT: f32 = 65536.0;

@compute @workgroup_size()" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << R"()
fn CSNormalAccum(@builtin(global_invocation_id) gid: vec3<u32>) {
  let tri = gid.x;
  if (tri >= uniforms.tri_count) { return; }   // workgroup early-exit

  let i0 = indices[tri * 3u];
  let i1 = indices[tri * 3u + 1u];
  let i2 = indices[tri * 3u + 2u];

  // Read positions as individual f32 scalars, then construct vec3.
  let b0 = i0 * uniforms.vertex_stride + uniforms.pos_offset;
  let b1 = i1 * uniforms.vertex_stride + uniforms.pos_offset;
  let b2 = i2 * uniforms.vertex_stride + uniforms.pos_offset;
  let p0 = vec3f(positions[b0], positions[b0 + 1u], positions[b0 + 2u]);
  let p1 = vec3f(positions[b1], positions[b1 + 1u], positions[b1 + 2u]);
  let p2 = vec3f(positions[b2], positions[b2 + 1u], positions[b2 + 2u]);

  let n = cross(p1 - p0, p2 - p0);   // unnormalised face normal

  // Quantise to i32 and atomicAdd — thread-safe accumulation across triangles.
  let ni = vec3i(i32(n.x * QUANT), i32(n.y * QUANT), i32(n.z * QUANT));
  for (var k = 0u; k < 3u; k = k + 1u) {
    let vi = select(select(i0, i1, k == 1u), i2, k == 2u);
    atomicAdd(&normals_acc[vi * 3u],      ni.x);
    atomicAdd(&normals_acc[vi * 3u + 1u], ni.y);
    atomicAdd(&normals_acc[vi * 3u + 2u], ni.z);
  }
}

// PASS 2 of 2: dequantise and normalise.
// Dispatch: ceil(vertex_count / 64) × 1 × 1

@group(0) @binding(3) var<storage, read_write> normals_out: array<f32>; // write as scalars

@compute @workgroup_size()" << d.threads[0] << ", 1, 1)\n"
      << R"(fn CSNormalNorm(@builtin(global_invocation_id) gid: vec3<u32>) {
  let vi = gid.x;
  if (vi >= uniforms.vertex_count) { return; }

  let raw = vec3f(
    f32(atomicLoad(&normals_acc[vi * 3u]))      / QUANT,
    f32(atomicLoad(&normals_acc[vi * 3u + 1u])) / QUANT,
    f32(atomicLoad(&normals_acc[vi * 3u + 2u])) / QUANT,
  );
  let n = normalize(raw);
  let base = vi * uniforms.vertex_stride + uniforms.pos_offset;  // reuse layout
  normals_out[base]      = n.x;
  normals_out[base + 1u] = n.y;
  normals_out[base + 2u] = n.z;
}
)";
        return true;
    }

    // ── needsTangentFrame ─────────────────────────────────────────────────────
    // Computes tangent + bitangent from position / normal / uv scalar arrays.
    // One thread per triangle; results written per-vertex (last-write wins for
    // shared vertices — acceptable for smooth meshes).
    if (d.needsTangentFrame) {
        f << R"(
// Tangent frame — scalar arrays, stride/offset uniforms (f32 element units).
// Dispatch: ceil(tri_count / 64) × 1 × 1

struct TangentUniforms {
  tri_count    : u32,
  vertex_stride: u32,
  pos_offset   : u32,
  uv_offset    : u32,   // UV is vec2 — 2 f32 elements
  tan_offset   : u32,   // tangent output slot (3 f32)
  bitan_offset : u32,   // bitangent output slot (3 f32)
};

@group(0) @binding(0) var<uniform>             uniforms: TangentUniforms;
@group(0) @binding(1) var<storage, read>       vb      : array<f32>;   // interleaved, scalar
@group(0) @binding(2) var<storage, read>       indices : array<u32>;
@group(0) @binding(3) var<storage, read_write> vb_out  : array<f32>;

@compute @workgroup_size()" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << R"()
fn CSMain(@builtin(global_invocation_id) gid: vec3<u32>) {
  let tri = gid.x;
  if (tri >= uniforms.tri_count) { return; }

  let i0 = indices[tri * 3u];
  let i1 = indices[tri * 3u + 1u];
  let i2 = indices[tri * 3u + 2u];

  let b0p = i0 * uniforms.vertex_stride + uniforms.pos_offset;
  let b1p = i1 * uniforms.vertex_stride + uniforms.pos_offset;
  let b2p = i2 * uniforms.vertex_stride + uniforms.pos_offset;
  let p0 = vec3f(vb[b0p], vb[b0p+1u], vb[b0p+2u]);
  let p1 = vec3f(vb[b1p], vb[b1p+1u], vb[b1p+2u]);
  let p2 = vec3f(vb[b2p], vb[b2p+1u], vb[b2p+2u]);

  let b0u = i0 * uniforms.vertex_stride + uniforms.uv_offset;
  let b1u = i1 * uniforms.vertex_stride + uniforms.uv_offset;
  let b2u = i2 * uniforms.vertex_stride + uniforms.uv_offset;
  let uv0 = vec2f(vb[b0u], vb[b0u+1u]);
  let uv1 = vec2f(vb[b1u], vb[b1u+1u]);
  let uv2 = vec2f(vb[b2u], vb[b2u+1u]);

  let dp1  = p1 - p0;   let dp2  = p2 - p0;
  let duv1 = uv1 - uv0; let duv2 = uv2 - uv0;

  let det = duv1.x * duv2.y - duv2.x * duv1.y;
  let inv = select(0.0, 1.0 / det, abs(det) > 1e-6);

  let tan   = normalize((dp1 * duv2.y - dp2 * duv1.y) * inv);
  let bitan = normalize((dp2 * duv1.x - dp1 * duv2.x) * inv);

  for (var k = 0u; k < 3u; k = k + 1u) {
    let vi = select(select(i0, i1, k == 1u), i2, k == 2u);
    let bt = vi * uniforms.vertex_stride + uniforms.tan_offset;
    let bb = vi * uniforms.vertex_stride + uniforms.bitan_offset;
    vb_out[bt]      = tan.x;   vb_out[bt+1u] = tan.y;   vb_out[bt+2u] = tan.z;
    vb_out[bb]      = bitan.x; vb_out[bb+1u] = bitan.y; vb_out[bb+2u] = bitan.z;
  }
}
)";
        return true;
    }

    // ── needsMeshlet ──────────────────────────────────────────────────────────
    // Per-meshlet frustum-sphere + backface cone cull.
    // Mirrors MeshletAS.hlsl from d3d12-meshlets/ using WebGPU compute.
    // Output: visibility bitmask array<u32> (1 bit per meshlet, packed).
    if (d.needsMeshlet) {
        f << R"(
// Meshlet culling — frustum sphere test + backface cone test.
// Dispatch: ceil(meshlet_count / 64) × 1 × 1

struct MeshletUniforms {
  meshlet_count: u32,
  // Row-major view-projection matrix as scalar f32 array (16 elements).
  // Avoids mat4x4f alignment constraints in uniform structs.
  vp: array<f32, 16>,
};

struct MeshletBounds {
  center_x : f32, center_y : f32, center_z : f32, radius    : f32,
  apex_x   : f32, apex_y   : f32, apex_z   : f32,
  axis_x   : f32, axis_y   : f32, axis_z   : f32, cone_cutoff: f32,
};

@group(0) @binding(0) var<uniform>             uniforms  : MeshletUniforms;
@group(0) @binding(1) var<storage, read>       bounds    : array<MeshletBounds>;
@group(0) @binding(2) var<storage, read_write> visibility: array<atomic<u32>>; // packed bits

fn vp_mul(vp: array<f32, 16>, v: vec4f) -> vec4f {
  return vec4f(
    vp[0]*v.x + vp[1]*v.y + vp[2]*v.z  + vp[3]*v.w,
    vp[4]*v.x + vp[5]*v.y + vp[6]*v.z  + vp[7]*v.w,
    vp[8]*v.x + vp[9]*v.y + vp[10]*v.z + vp[11]*v.w,
    vp[12]*v.x+ vp[13]*v.y+ vp[14]*v.z + vp[15]*v.w,
  );
}

@compute @workgroup_size()" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << R"()
fn CSMain(@builtin(global_invocation_id) gid: vec3<u32>) {
  let mi = gid.x;
  if (mi >= uniforms.meshlet_count) { return; }

  let mb = bounds[mi];
  let center = vec3f(mb.center_x, mb.center_y, mb.center_z);

  // Frustum sphere test: project centre + radius against 6 clip planes.
  let clip = vp_mul(uniforms.vp, vec4f(center, 1.0));
  let w    = clip.w;
  var visible = (clip.x >= -w - mb.radius) && (clip.x <= w + mb.radius)
             && (clip.y >= -w - mb.radius) && (clip.y <= w + mb.radius)
             && (clip.z >=  0.0 - mb.radius) && (clip.z <= w + mb.radius);

  // Backface cone test: if cone faces fully away from camera, cull.
  if (visible) {
    let apex     = vec3f(mb.apex_x, mb.apex_y, mb.apex_z);
    let axis     = vec3f(mb.axis_x, mb.axis_y, mb.axis_z);
    let view_dir = normalize(-apex);  // approximate; replace with per-instance camera dir
    visible = dot(view_dir, -axis) < mb.cone_cutoff;
  }

  if (visible) {
    let word = mi / 32u;
    let bit  = mi % 32u;
    atomicOr(&visibility[word], 1u << bit);
  }
}
)";
        return true;
    }

    // ── needsVertexProcess ────────────────────────────────────────────────────
    // Generic scalar-array vertex processing with stride/offset uniforms.
    // Template for transform, scale, remap, pack operations.
    if (d.needsVertexProcess) {
        f << R"(
// Generic vertex processing — scalar f32 arrays, stride/offset in f32 units.
// Dispatch: ceil(vertex_count / )" << d.threads[0] << R"() × 1 × 1

struct VertexUniforms {
  vertex_count: u32,
  in_stride   : u32,   // f32 elements between consecutive vertices in input
  in_offset   : u32,   // f32 elements from vertex start to first attribute
  out_stride  : u32,
  out_offset  : u32,
  scale       : f32,
};

@group(0) @binding(0) var<uniform>             uniforms  : VertexUniforms;
@group(0) @binding(1) var<storage, read>       vert_in   : array<f32>;
@group(0) @binding(2) var<storage, read_write> vert_out  : array<f32>;

@compute @workgroup_size()" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << R"()
fn CSMain(@builtin(global_invocation_id) gid: vec3<u32>) {
  let vi = gid.x;
  if (vi >= uniforms.vertex_count) { return; }   // workgroup early-exit

  let src = vi * uniforms.in_stride  + uniforms.in_offset;
  let dst = vi * uniforms.out_stride + uniforms.out_offset;

  // Read as individual scalars — avoid vec3f alignment (16-byte in WGSL).
  let x = vert_in[src];
  let y = vert_in[src + 1u];
  let z = vert_in[src + 2u];

  vert_out[dst]      = x * uniforms.scale;
  vert_out[dst + 1u] = y * uniforms.scale;
  vert_out[dst + 2u] = z * uniforms.scale;
}
)";
        return true;
    }

    // ── default (attention / phase / generic) ─────────────────────────────────
    f << "struct Params {\n";
    f << "  seq_len    : u32,\n  model_dim  : u32,\n  head_dim   : u32,\n";
    f << "  scale      : f32,\n  num_experts: u32,\n  phase_words: u32,\n};\n\n";
    f << "@group(0) @binding(0) var<uniform>            params     : Params;\n";
    f << "@group(0) @binding(1) var<storage, read>      input_data : array<f32>;\n";
    f << "@group(0) @binding(2) var<storage, read_write>output_data: array<f32>;\n\n";
    f << "@compute @workgroup_size(" << d.threads[0] << ", " << d.threads[1] << ", " << d.threads[2] << ")\n";
    f << "fn CSMain(@builtin(global_invocation_id) gid: vec3<u32>) {\n";
    f << "  let i = gid.x;\n";
    f << "  if (i >= params.seq_len) { return; }\n";
    if (d.needsMatMul && d.needsSoftmax) {
        f << "  // Scaled dot-product attention — accumulate then softmax.\n";
        f << "  var acc = 0.0f;\n";
        f << "  for (var k = 0u; k < params.head_dim; k = k + 1u) {\n";
        f << "    acc += input_data[i * params.head_dim + k] * input_data[k];\n";
        f << "  }\n";
        f << "  output_data[i] = acc * params.scale;\n";
    } else if (d.needsMatMul) {
        f << "  var acc = 0.0f;\n";
        f << "  for (var k = 0u; k < params.model_dim; k = k + 1u) {\n";
        f << "    acc += input_data[i * params.model_dim + k] * input_data[k];\n";
        f << "  }\n";
        f << "  output_data[i] = acc;\n";
    } else if (d.needsPhaseMatch) {
        f << "  let x  = input_data[i];\n";
        f << "  let dx = input_data[i + params.seq_len];\n";
        f << "  output_data[i] = x + 0.01 * dx;\n";
    } else {
        f << "  output_data[i] = input_data[i];\n";
    }
    f << "}\n";
    return true;
}
