// Generated by kxc for kernel binary_split
// variant=shared
cbuffer Params : register(b0)
{
    uint seq_len;
    uint model_dim;
    uint head_dim;
    float scale;
    uint num_experts;
    uint phase_words;
};

StructuredBuffer<float> X : register(t0);
StructuredBuffer<float> Wqkv : register(t1);
RWStructuredBuffer<float> Out : register(u0);

[numthreads(32, 1, 1)]
void CSMain(uint3 tid : SV_DispatchThreadID)
{
    uint i = tid.x;
    if (i >= seq_len) return;
    float acc = 0.0f;
    for (uint d = 0; d < min(model_dim, head_dim); ++d) {
        float x = X[i * model_dim + d];
        float w = Wqkv[d * (3 * head_dim) + d];
        acc += x * w;
    }
    Out[i * head_dim] = acc;
}
