// Generated by KLSL compiler v0.1
// Shader: dense_layer

StructuredBuffer<float> input_buf : register(t0);
StructuredBuffer<float> weight_buf : register(t1);
StructuredBuffer<float> bias_buf : register(t2);
RWStructuredBuffer<float> out_buf : register(u0);
ConstantBuffer<DenseConst> cb : register(b0);

// neural_layer.klsl
// Dense (fully-connected) neural network layer as a KLSL compute shader.
//
// Compile:  klslc neural_layer.klsl
// Output:   neural_layer.hlsl  (dispatch with [16,16,1] thread groups)
//
// cbuffer layout (DenseConst):
//   uint in_dim;    // K
//   uint out_rows;  // M  (batch)
//   uint out_cols;  // N  (output neurons)
//   uint _pad;




[numthreads(16, 16, 1)]
void dense_forward(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint row = SV_DispatchThreadID.y;
    uint col = SV_DispatchThreadID.x;
    if (row >= cb.out_rows || col >= cb.out_cols) return;

    float acc = 0.0f;
    for (uint k = 0; k < cb.in_dim; ++k) {
        float a = input_buf[row * cb.in_dim + k];
        float w = weight_buf[col * cb.in_dim + k];
        acc += a * w;
    }

    // Add bias + ReLU activation
    acc += bias_buf[col];
    if (acc < 0.0f) acc = 0.0f;
    out_buf[row * cb.out_cols + col] = acc;
}


