// Generated by KLSL compiler v0.1
// Shader: neural_layer_kuhul

StructuredBuffer<float> X_buf : register(t0);
StructuredBuffer<float> W_buf : register(t1);
StructuredBuffer<float> b_buf : register(t2);
RWStructuredBuffer<float> out_buf : register(u0);
ConstantBuffer<LayerConst> cb : register(b0);

// neural_layer_kuhul.klsl
// K'UHUL linear layer: out[r,j] = sum_k(X[r,k] * W[k,j]) + b[j]
//
// Phase contract (Pop → Wo → Yax → Sek → Ch'en → Xul):
//   Wo        — declares all tensor buffers; W and b are independent peers at own register slots
//   Yax       — annotates operand load  (comment in HLSL, Yax phase signal in runtime)
//   Sek       — dispatches compute: ⊗ accumulation per k, ⊕ bias-add
//   Ch'en     — annotates result store  (comment in HLSL, Ch'en phase signal in runtime)
//   K'ayab'   — for-loop over in_dim  (KLSL loop construct, not a runtime phase)
//   Kumk'u    — end loop
//
// Tensor shapes (safe contract — no invented semantics):
//   X_buf : [n_rows * in_dim]   layout [r, k],  r = B*T row, k = input channel
//   W_buf : [out_dim * in_dim]  layout [j, k],  j = output neuron (col-major per neuron)
//   b_buf : [out_dim]           own buffer t2 — bias is its own weight matrix, not a column of W
//   out_buf: [n_rows * out_dim] layout [r, j]
//
// cbuffer LayerConst:
//   uint in_dim;   // K = 1024
//   uint out_dim;  // N = 512
//   uint n_rows;   // B * T (batch * sequence length)
//   uint _pad;
//
// Compile:  klslc neural_layer_kuhul.klsl neural_layer_kuhul.hlsl
// Dispatch: (ceil(out_dim/16), ceil(n_rows/16), 1) thread groups



// Wo: declare all weight tensors — W and b are peer buffers with independent register slots

[numthreads(16, 16, 1)]
void neural_forward(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint col = SV_DispatchThreadID.x;
    uint row = SV_DispatchThreadID.y;
    if (col >= cb.out_dim || row >= cb.n_rows) return;

    // Sek ⊗: X ⊗ W — dot product over in_dim
    // [← X_buf W_buf]
    float acc = 0.0f;
    for (uint k = 0; k < cb.in_dim; ++k) {
        float x_k = X_buf[row * cb.in_dim + k];
        float w_k = W_buf[col * cb.in_dim + k];
        acc += x_k * w_k;
    }
    // [→ XW]

    // Sek ⊕: b_buf is its own independent weight buffer (t2), not a column of W
    // [← b_buf]
    float b_j = b_buf[col];
    acc += b_j;
    // [→ output]
    out_buf[row * cb.out_dim + col] = acc;
}


