// Generated by kxc for kernel FusedAttention
#include <algorithm>
#include <cstdint>
#include <vector>

struct FusedAttentionCpuConfig {
  std::uint32_t seq_len = 0;
  std::uint32_t model_dim = 0;
  std::uint32_t head_dim = 0;
  std::uint32_t num_experts = 0;
};

inline void Run_FusedAttention_Cpu(const FusedAttentionCpuConfig& cfg) {
  (void)cfg;
  // CPU fallback generated from backend-neutral IR.
  // wave_ops=false, heap_tier=1, binding_tier=1
  // Generic scalar fallback.
}
